name: Deploy Angular

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build --prod

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Add known hosts
        run: |
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Create project folder on VPS
        run: |
          PROJECT_NAME="${GITHUB_REPOSITORY#*/}"
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p /root/proyectos/$PROJECT_NAME/"

      - name: Deploy build via rsync
        run: |
          PROJECT_NAME="${GITHUB_REPOSITORY#*/}"
          rsync -avz --delete dist/browser/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/root/proyectos/$PROJECT_NAME/

      - name: Run Angular on port 4200 (http-server)
        run: |
          PROJECT_NAME="${GITHUB_REPOSITORY#*/}"
      
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            pkill -f http-server || true
            nohup http-server /root/proyectos/$PROJECT_NAME \
              -p 4200 \
              --spa \
              --host 0.0.0.0 \
              > /tmp/http-server.log 2>&1 &
          "
